import {ArrowUpRight,ArrowRight,FileCheck2,FlaskConical,ShieldCheck,Package,Truck,MessageCircle,Clock} from 'lucide-react';
import source from '@/content/source-pages.json';
import article from '@/content/reta-article.json';

export function PolicyPage({slug}:{slug:'privacy-policy'|'terms-conditions'}){const page=source.pages.find(p=>p.slug===slug)!;const html=(value:string)=>value.replace(/https:\/\/innoaminos\.com\/(privacy-policy|terms-conditions|why-us|faq|contact)\/?/g,'/$1').replace('<a>support.lab@innoaminos.com</a>','<a href="mailto:support.lab@innoaminos.com">support.lab@innoaminos.com</a>');return <main id="main-content"><div className="page-intro compact legal-intro"><span className="glass-pill">INNO AMINOS · POLICIES</span><h1>{page.title}</h1><p>Our published terms for laboratory research purchases.</p></div><div className="policy-layout"><nav aria-label="On this page"><span className="eyebrow">ON THIS PAGE</span>{page.sections.map((section,i)=>section.heading&&<a key={i} href={'#section-'+i}>{section.heading}</a>)}<a href="/contact">Questions? Contact us <ArrowUpRight size={14}/></a></nav><article className="policy-content">{page.sections.map((section,i)=><section id={'section-'+i} key={i}>{section.heading&&<h2>{section.heading}</h2>}<div dangerouslySetInnerHTML={{__html:html(section.html)}}/></section>)}</article></div></main>}

export function WhyUsPage(){const page=source.pages.find(p=>p.slug==='why-us')!;const icons=[FlaskConical,FileCheck2,Truck,ShieldCheck,Package,MessageCircle];return <main id="main-content"><section className="why-hero"><div><span className="glass-pill"><ShieldCheck size={16}/> THE INNO STANDARD</span><h1>High standards.<br/><em>Clear evidence.</em></h1><p>Research deserves more than a label. It deserves careful testing, clear documentation, and people who stand behind the details.</p><a className="btn" href="/#collection">Explore the collection <ArrowUpRight size={18}/></a></div><div className="why-image"><img src="/products/inno-3-rt.png" alt="INNO-3 RT research peptide"/><span className="glass-pill"><FileCheck2 size={17}/> COAs on every product page</span></div></section><section className="section"><div className="section-heading"><div><span className="eyebrow">WHAT GOES INTO EVERY ORDER</span><h2>Small details.<br/>A higher standard.</h2></div></div><div className="why-grid">{page.sections.map((section,i)=>{const Icon=icons[i%icons.length];return <article key={i}><Icon size={28}/><h3>{section.heading}</h3><div dangerouslySetInnerHTML={{__html:section.html}}/></article>})}</div></section><div className="why-bottom"><FileCheck2 size={36}/><div><h2>See the evidence for yourself.</h2><p>Open the COA viewer on any product page to browse the reports. Confirm the applicable batch before ordering.</p></div><a href="/inno-3-rt" className="btn secondary">Start with INNO-3 RT <ArrowRight size={18}/></a></div></main>}

function LinkedParagraph({text}:{text:string}){const parts=text.split(/(\[[^\]]+\]\([^)]+\))/g);return <>{parts.map((part,i)=>{const match=part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);if(!match)return <span key={i}>{part}</span>;const url=match[2];return url.startsWith('/')?<a key={i} href={url}>{match[1]}</a>:url.startsWith('https://')?<a key={i} href={url} target="_blank" rel="noreferrer">{match[1]}</a>:<span key={i}>{match[1]}</span>})}</>}
export function BlogIndex(){return <main id="main-content"><div className="page-intro journal-intro"><span className="glass-pill">THE INNO JOURNAL</span><h1>For the<br/><em>curious minds.</em></h1><p>Peptide research, clearer context, and a closer look at what’s inside the vial.</p></div><section className="blog-index-body"><a className="featured-article" href={'/blog/'+article.slug}><div className="article-art"><span className="glass-pill">RESEARCH NOTES · 001</span><h2>Reta,<br/><em>explained.</em></h2><img src="/products/inno-3-rt.png" alt="INNO-3 RT research peptide vial"/></div><div className="featured-article-copy"><span className="eyebrow">PEPTIDE RESEARCH</span><h2>Reta research: a closer look at INNO-3 RT.</h2><p>{article.deck}</p><div className="article-meta"><span>September 14, 2026</span><span><Clock size={14}/> {article.readingMinutes} min read</span></div><span className="text-link">Read the research note <ArrowUpRight size={18}/></span></div></a></section></main>}
export function BlogArticle(){return <main id="main-content"><header className="article-header"><a href="/blog" className="text-link">The Inno Journal <ArrowUpRight size={15}/></a><div className="glass-pill">PEPTIDE RESEARCH · 001</div><h1>Reta, explained.<br/><em>Look beyond the label.</em></h1><p>{article.deck}</p><div className="article-meta"><span>Inno Aminos Editorial</span><span>September 14, 2026</span><span>{article.readingMinutes} min read</span></div></header><div className="article-layout"><aside><span className="eyebrow">IN THIS ARTICLE</span>{article.sections.map((section,i)=><a key={i} href={'#article-section-'+i}>{section.heading}</a>)}</aside><article className="article-content">{article.sections.map((section,i)=><section key={i} id={'article-section-'+i}><h2>{section.heading}</h2>{section.paragraphs.map((p,j)=><p key={j}><LinkedParagraph text={p}/></p>)}</section>)}<div className="article-product-cta"><img src="/products/inno-3-rt.png" alt="INNO-3 RT vial"/><div><span className="eyebrow">NEXT, THE DETAILS.</span><h2>Explore INNO-3 RT.</h2><p>10 mg, 20 mg, and 30 mg sizes. Published COAs. Flexible quantities.</p><a href="/inno-3-rt" className="btn">View INNO-3 RT <ArrowRight size={18}/></a><span>For laboratory research only. Not for human or animal use.</span></div></div><div className="article-sources"><h3>Sources & further reading</h3>{article.sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{i+1}. {s.label}<ArrowUpRight size={14}/></a>)}</div></article></div></main>}
