import {storeMode} from './store-config';
export type Plan = 'once' | 'monthly' | 'quarterly';
export type Variant = { name: string; price: number; coa?: string; available?: boolean };
export type Product = { slug: string; name: string; category: string; subtitle: string; description: string; image: string; variants: Variant[]; details: string; source: string; coa?: string; accessory?: boolean };
export const products: Product[] = [
 {slug:'inno-3-rt',name:'INNO-3 RT',category:'Research peptide',subtitle:'Our bestselling research peptide.',description:'Available in three sizes, with straightforward savings when you stock up. Select your vial size, choose your quantity, and order on your schedule.',image:'/products/inno-3-rt.png',variants:[{name:'10 mg',price:8499,coa:'https://innoaminos.com/wp-content/uploads/2025/11/retastell10test.png'},{name:'20 mg',price:15999,coa:'https://innoaminos.com/wp-content/uploads/2025/11/rt20test.png'},{name:'30 mg',price:21999,coa:'https://innoaminos.com/wp-content/uploads/2026/06/RT30test.png'}],details:'INNO-3 RT is supplied for laboratory research. Choose 10 mg, 20 mg, or 30 mg per vial. Product photography represents the range; your selected size is shown in the order summary.',source:'https://innoaminos.com/product/inno-3-rt/'},
 {slug:'tesamorelin',coa:'https://innoaminos.com/wp-content/uploads/2025/11/Tesatestpass.png',name:'Tesamorelin',category:'Research peptide',subtitle:'A focused addition to your research.',description:'Tesamorelin, supplied in a 10 mg vial for laboratory research. Order individually or add it to a custom box to unlock quantity savings.',image:'/products/tesamorelin.png',variants:[{name:'10 mg',price:7699}],details:'Each vial contains 10 mg Tesamorelin. Supplied for laboratory research only; not for human or animal use.',source:'https://innoaminos.com/product/tesamorelin/'},
 {slug:'mots-c',coa:'https://innoaminos.com/wp-content/uploads/2025/11/MOTScapriltest.png',name:'MOTS-c',category:'Research peptide',subtitle:'Small vial. More possibilities for research.',description:'MOTS-c, supplied in a 10 mg vial for laboratory research. Choose a single product or mix it with the rest of your research essentials.',image:'/products/mots-c.png',variants:[{name:'10 mg',price:4999}],details:'Each vial contains 10 mg MOTS-c. Supplied for laboratory research only; not for human or animal use.',source:'https://innoaminos.com/product/mots-c/'},
 {slug:'klow',coa:'https://innoaminos.com/wp-content/uploads/2026/06/KlowCOA.png',name:'KLOW',category:'Research blend',subtitle:'Four compounds. One research blend.',description:'An 80 mg research blend of GHK-Cu, BPC-157, TB-500, and KPV. Select your quantity or include it in your custom research box.',image:'/products/klow-80mg.png',variants:[{name:'80 mg',price:12999}],details:'80 mg total per vial: GHK-Cu 50 mg, BPC-157 10 mg, TB-500 10 mg, and KPV 10 mg. For laboratory research only.',source:'https://innoaminos.com/product/klow/'},
 {slug:'wolverine',coa:'https://innoaminos.com/wp-content/uploads/2026/07/bpctbtest.webp',name:'The Wolverine Pack',category:'Research blend',subtitle:'BPC-157 + TB-500, together.',description:'The BPC-157 / TB-500 blend, now called The Wolverine Pack. Two compounds in a single vial, with the same simple quantity savings as the rest of the collection.',image:'/products/wolverine.png',variants:[{name:'20 mg',price:9499}],details:'The Wolverine Pack is one blend vial containing 10 mg BPC-157 and 10 mg TB-500, 20 mg combined. Pack refers to this blend, not two separate vials. Supplied strictly for laboratory research.',source:'https://innoaminos.com/product/bpc-157-tb-500-wolverine-stack/'},
 {slug:'reconstitution-solution',coa:'https://innoaminos.com/wp-content/uploads/2026/01/BacWater.png',name:'Amino BAC Water',category:'Laboratory essential',subtitle:'The finishing touch for your research box.',description:'10 mL bacteriostatic reconstitution solution for laboratory use. Included free with 3+ qualifying peptide items in the same shipment, or available as a $10 cart add-on with a smaller peptide order.',image:'/products/bac-10ml.png',variants:[{name:'10 mL',price:1999}],details:'10 mL reconstitution solution. Laboratory use only. BAC does not count toward peptide quantity discounts. One complimentary bottle per qualifying shipment.',source:'https://innoaminos.com/product/recon-10-ml/',accessory:true},
];
export const money = (cents:number) => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export const rate = (quantity:number,plan:Plan):number => quantity<=0?0:storeMode==='box'?[15,20,30,35,40][Math.min(quantity,5)-1]:storeMode==='get'?(quantity===2?25:quantity>=3?100/3:0):({once:[15,20,30],monthly:[20,25,35],quarterly:[30,35,40]}[plan][Math.min(quantity,3)-1]);
export const getOfferTotal=(base:number,quantity:number)=>quantity===2?base+Math.round(base/2):quantity===3?base*2:base*quantity;
export const discounted = (price:number,percent:number) => Math.round(price*(100-percent)/100);
export const planText = (plan:Plan) => ({once:'One-time purchase',monthly:'Every month',quarterly:'Every 3 months'}[plan]);
export type Line = {slug:string; variant:number; quantity:number; plan:Plan};
export function priceCart(lines:Line[],bacAddon=false,catalog:Product[]=products){
 const counts:Record<Plan,number>={once:0,monthly:0,quarterly:0};
 for(const l of lines) if(!catalog.find(p=>p.slug===l.slug)?.accessory) counts[l.plan]+=l.quantity;
 const gifts=(Object.keys(counts) as Plan[]).filter(p=>(storeMode==='shop'||storeMode==='box')&&counts[p]>=3);
 const priced=lines.map(l=>{const p=catalog.find(p=>p.slug===l.slug)!; const base=p.variants[l.variant].price;const percent=p.accessory?0:rate(counts[l.plan],l.plan);const total=storeMode==='get'&&!p.accessory?getOfferTotal(base,l.quantity):discounted(base,percent)*l.quantity;return {...l,product:p,base,percent,unit:total/l.quantity,total}});
 const original=priced.reduce((s,l)=>s+l.base*l.quantity,0);
 const peptides=Object.values(counts).reduce((a,b)=>a+b,0);
 const addon=bacAddon&&peptides>0&&gifts.length===0?1000:0;
 const subtotal=priced.reduce((s,l)=>s+l.total,0)+addon;
 return {counts,gifts,priced,original,peptides,addon,subtotal,savings:original-priced.reduce((s,l)=>s+l.total,0)};
}
